version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "build(deps): "
    open-pull-requests-limit: 50
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "build(deps): "
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "storybook"
      - dependency-name: "@storybook/*"
